"""modelo incial rpas

Revision ID: 4fc40386fe85
Revises: 
Create Date: 2026-02-26 19:58:05.740736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc40386fe85'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formas_operacao',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('nome'),
    schema='rpas'
    )
    op.create_index(op.f('ix_rpas_formas_operacao_nome'), 'formas_operacao', ['nome'], unique=True, schema='rpas')
    op.create_table('operadoras',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('nome'),
    schema='rpas'
    )
    op.create_index(op.f('ix_rpas_operadoras_nome'), 'operadoras', ['nome'], unique=True, schema='rpas')
    op.create_table('processos',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('nome'),
    schema='rpas'
    )
    op.create_index(op.f('ix_rpas_processos_nome'), 'processos', ['nome'], unique=True, schema='rpas')
    op.create_table('produtos',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('nome'),
    schema='rpas'
    )
    op.create_index(op.f('ix_rpas_produtos_nome'), 'produtos', ['nome'], unique=True, schema='rpas')
    op.create_table('retencao_carteirinhas',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('nome'),
    schema='rpas'
    )
    op.create_index(op.f('ix_rpas_retencao_carteirinhas_nome'), 'retencao_carteirinhas', ['nome'], unique=True, schema='rpas')
    op.create_table('status',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('nome'),
    schema='rpas'
    )
    op.create_index(op.f('ix_rpas_status_nome'), 'status', ['nome'], unique=True, schema='rpas')
    op.create_table('status_acessos',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('nome'),
    schema='rpas'
    )
    op.create_index(op.f('ix_rpas_status_acessos_nome'), 'status_acessos', ['nome'], unique=True, schema='rpas')
    op.create_table('tipos_contrato',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('nome'),
    schema='rpas'
    )
    op.create_index(op.f('ix_rpas_tipos_contrato_nome'), 'tipos_contrato', ['nome'], unique=True, schema='rpas')
    op.create_table('tipos_rpa',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('nome'),
    schema='rpas'
    )
    op.create_index(op.f('ix_rpas_tipos_rpa_nome'), 'tipos_rpa', ['nome'], unique=True, schema='rpas')
    op.create_table('rpas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('operadora_nome', sa.String(), nullable=False),
    sa.Column('produto_nome', sa.String(), nullable=False),
    sa.Column('tipo_contrato_nome', sa.String(), nullable=False),
    sa.Column('processo_nome', sa.String(), nullable=False),
    sa.Column('tipo_rpa_nome', sa.String(), nullable=False),
    sa.Column('status_nome', sa.String(), nullable=False),
    sa.Column('status_detalhe', sa.String(), nullable=True),
    sa.Column('status_last_update', sa.DateTime(), nullable=True),
    sa.Column('retencao_carteirinha_nome', sa.String(), nullable=False),
    sa.Column('doc_baixa', sa.String(), nullable=True),
    sa.Column('forma_operacao_nome', sa.String(), nullable=False),
    sa.Column('status_acesso_nome', sa.String(), nullable=False),
    sa.Column('status_acesso_detalhe', sa.String(), nullable=True),
    sa.Column('status_acesso_last_update', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forma_operacao_nome'], ['rpas.formas_operacao.nome'], ),
    sa.ForeignKeyConstraint(['operadora_nome'], ['rpas.operadoras.nome'], ),
    sa.ForeignKeyConstraint(['processo_nome'], ['rpas.processos.nome'], ),
    sa.ForeignKeyConstraint(['produto_nome'], ['rpas.produtos.nome'], ),
    sa.ForeignKeyConstraint(['retencao_carteirinha_nome'], ['rpas.retencao_carteirinhas.nome'], ),
    sa.ForeignKeyConstraint(['status_acesso_nome'], ['rpas.status_acessos.nome'], ),
    sa.ForeignKeyConstraint(['status_nome'], ['rpas.status.nome'], ),
    sa.ForeignKeyConstraint(['tipo_contrato_nome'], ['rpas.tipos_contrato.nome'], ),
    sa.ForeignKeyConstraint(['tipo_rpa_nome'], ['rpas.tipos_rpa.nome'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='rpas'
    )
    op.create_index(op.f('ix_rpas_rpas_id'), 'rpas', ['id'], unique=True, schema='rpas')
    op.create_index(op.f('ix_rpas_rpas_nome'), 'rpas', ['nome'], unique=True, schema='rpas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rpas_rpas_nome'), table_name='rpas', schema='rpas')
    op.drop_index(op.f('ix_rpas_rpas_id'), table_name='rpas', schema='rpas')
    op.drop_table('rpas', schema='rpas')
    op.drop_index(op.f('ix_rpas_tipos_rpa_nome'), table_name='tipos_rpa', schema='rpas')
    op.drop_table('tipos_rpa', schema='rpas')
    op.drop_index(op.f('ix_rpas_tipos_contrato_nome'), table_name='tipos_contrato', schema='rpas')
    op.drop_table('tipos_contrato', schema='rpas')
    op.drop_index(op.f('ix_rpas_status_acessos_nome'), table_name='status_acessos', schema='rpas')
    op.drop_table('status_acessos', schema='rpas')
    op.drop_index(op.f('ix_rpas_status_nome'), table_name='status', schema='rpas')
    op.drop_table('status', schema='rpas')
    op.drop_index(op.f('ix_rpas_retencao_carteirinhas_nome'), table_name='retencao_carteirinhas', schema='rpas')
    op.drop_table('retencao_carteirinhas', schema='rpas')
    op.drop_index(op.f('ix_rpas_produtos_nome'), table_name='produtos', schema='rpas')
    op.drop_table('produtos', schema='rpas')
    op.drop_index(op.f('ix_rpas_processos_nome'), table_name='processos', schema='rpas')
    op.drop_table('processos', schema='rpas')
    op.drop_index(op.f('ix_rpas_operadoras_nome'), table_name='operadoras', schema='rpas')
    op.drop_table('operadoras', schema='rpas')
    op.drop_index(op.f('ix_rpas_formas_operacao_nome'), table_name='formas_operacao', schema='rpas')
    op.drop_table('formas_operacao', schema='rpas')
    # ### end Alembic commands ###
